config/routes.rb
Rails.application.routes.draw do
  resources :post_images
  resources :comments

  devise_for :users

  get 'welcome/index'

  get  "/comments/:id/new(.:format)" => "comments#new"

  get  "/home" => "home#index"

  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post_image
end

app/models/post_image.rb
class PostImage < ActiveRecord::Base

  has_many :comments

  mount_uploader :name, PostImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment    = Comment.new
    @post_image = PostImage.find params[:id]
    @comments   = Comment.includes(:user).where post_image_id: @post_image.id
  end

  # GET /comments/1/edit
  def edit
    @post_image = PostImage.find @comment.post_image_id
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:description, :user_id, :post_image_id, :deleted_at)

    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @post_images = PostImage
        .where(visible: true)
        .where('open_date <= ?', Time.current)
        .where('close_date >= ?', Time.current)
        .page(params[:page])
        .per(Constants.POST_LIST_LIMIT)

    @comments    = Comment.all
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  before_action :set_post_image, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  respond_to :html

  def index
    @post_images = PostImage.where(user_id: current_user.id).page(params[:page]).per(Constants.POST_IMAGE_LIMIT)
    respond_with(@post_images)
  end

  def show
    return redirect_to root_path, alert: 'Not found' unless login_user?
    respond_with(@post_image)
  end

  def new
    @post_image = PostImage.new
    respond_with(@post_image)
  end

  def edit
    if @post_image.user_id != current_user.id
      redirect_to root_path, alert: 'Not found'
      return
    end
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.save
    respond_with(@post_image)
  end

  def update
    @post_image.update(post_image_params)
    respond_with(@post_image)
  end

  def destroy
    @post_image.destroy
    respond_with(@post_image)
  end

  private
    def set_post_image
      @post_image = PostImage.find(params[:id])
    end

    def post_image_params
      params.require(:post_image).permit(:name, :user_id, :description, :open_date, :close_date, :limit, :visible, :comment_able, :deleted_at)
    end

    def login_user?
      @post_image.user_id == current_user.id
    end
end

app/controllers/welcom_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper

 def link_to_if_with_block condition, options, html_options={}, &block
   if condition
     link_to options, html_options, &block
   else
     capture &block
   end
 end

end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/welcom_helper.rb
module WelcomHelper
end

app/views/application/_header.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-header">

    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

  <%=link_to root_path, class: "navbar-brand" do%><i class="glyphicon glyphicon-home"></i><% end %>
  </div>

  <div class="navbar-collapse collapse navbar-inverse-collapse">

    <ul class="nav navbar-nav">
      <li class="active"><a href="javascript:void(0)">Active</a></li>
      <li><a href="javascript:void(0)">Link</a></li>

      <li class="dropdown">
        <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
          Dropdown&nbsp;<b class="caret"></b>
        </a>

        <ul class="dropdown-menu">
          <li><%= link_to 'My Post Images', post_images_path %></li>
          <li><%= link_to 'home', home_path %></li>
          <li><a href="javascript:void(0)">Something else here</a></li>
          <li class="divider"></li>
          <li class="dropdown-header">Dropdown header</li>
          <li><a href="javascript:void(0)">Separated link</a></li>
          <li><a href="javascript:void(0)">One more separated link</a></li>
        </ul>
      </li>

    </ul>

    <form class="navbar-form navbar-left">
      <input type="text" class="form-control col-lg-8" placeholder="Search">
    </form>

    <ul class="nav navbar-nav navbar-right">

      <%- if user_signed_in? -%>

      <li class="dropdown">
        <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
          <%= current_user.email %>&nbsp;<b class="caret"></b>
        </a>

        <ul class="dropdown-menu">
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>

      <% else %>
      <li><%= link_to "Log in", new_user_session_path %></li>
      <%- end -%>

    </ul>

  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for(@comment, html: {class: 'form-horizontal'} ) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">

    <div class="col-md-8 col-xs-8">
      <div class="field">
        <% if @post_image.name %>
          <%= image_tag @post_image.name.url, class: "img-responsive" %>
        <% end %>
      </div>
    </div>

    <div class="col-md-4 col-xs-4">
      <div class="field">
        <%= f.label :description %><br>
        <%= f.text_field :description, class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit class: "btn btn-primary btn-lg"%>
      </div>
    </div>

  </div>

  <%= f.hidden_field :user_id,       value: current_user.id %>
  <%= f.hidden_field :post_image_id, value: @post_image.id %>

<% end %>

<div class="row">
  <div class="col-md-12 col-xs-12">
    <p>
      <%= @post_image.description %>
    </p>
  </div>
</div>

<table class="table table-striped table-hover ">
  <thead>
    <% @comments.each do |comment| %>
    <tr>
      <th class="col-xs-4 col-md-8">
        <%= comment.user.email %>
      </th>
      <td class="col-xs-4 col-md-8">
        <%= comment.description %>
      </td>
    </tr>
    <% end %>
  </thead>
</table>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-offset-1 col-md-10">
      <div class="well bs-component">
        <h1>New comment</h1>

        <%= render 'form' %>

        <%= link_to 'Back', comments_path, {class: "btn btn-default"}  %>

      </div>
    </div>
  </div>
</div>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/home/_home_td_discription.html.erb
<td class="col-md-4 col-xs-4">

  <p class="td-inner-top">
    <%= post_image.description %>
  </p>
  <p class="td-inner-middle">
    <% @comments.each do |comment| %>
      <%= comment.description if comment.post_image_id == post_image.id %>
    <% end %>
  </p>

</td>

app/views/home/_home_td_image.html.erb
<td class="col-md-8 col-xs-8">
  <%= link_to_if_with_block post_image.comment_able,
  ({controller: :comments, action: :new, id: post_image.id}) do %>
    <% if post_image.name %>
      <%= image_tag post_image.name.url, class: "img-responsive" %>
    <% end %>
  <% end %>
</td>

app/views/home/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-offset-1 col-xs-offset-1 col-md-10 col-xs-10">
      <div class="well bs-component">
        <h1>Home#index</h1>
        <table>
          <% @post_images.each.with_index do |post_image, index| %>
            <tr>
              <% if index % 2 == 0 %>
                <%= render partial:'home_td_image', locals: { post_image: post_image } %>
                <%= render partial:'home_td_discription', locals: { post_image: post_image, comments: @comments } %>
              <% else %>
                <%= render partial:'home_td_discription', locals: { post_image: post_image, comments: @comments } %>
                <%= render partial:'home_td_image', locals: { post_image: post_image } %>
              <% end %>
            </tr>
          <% end %>
        </table>
        <%= paginate @post_images %>

      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Barcelona</title>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
  <link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.2.0/css/ripples.min.css" rel="stylesheet">
  <link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.2.0/css/material.min.css" rel="stylesheet">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'header' %>

  <% if notice %>
  <p class="alert alert-success alert-dismissible"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p class="alert alert-danger alert-dismissible"><%= alert %></p>
  <% end %>

  <%= yield %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <script>
  $(function() {

    $('#datetimepicker1').datetimepicker();
    $('#datetimepicker2').datetimepicker();
    $.material.init();
    $('.dropdown-toggle').dropdown();

  });
  </script>

</body>
</html>

app/views/post_images/_form.html.erb
<%= form_for(@post_image, html: {class: 'form-horizontal'}) do |f| %>
<% if @post_image.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@post_image.errors.count, "error") %> prohibited this post_image from being saved:</h2>

  <ul>
    <% @post_image.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>


<div class="field form-group col-lg-10">
  <% if @post_image.name %>
    <%= image_tag @post_image.name.url, class: "img-responsive" %>
  <% end %>
  <%= f.label :name %><br>
  <input type="text" readonly="" class="form-control floating-label" placeholder="ファイルを選択...">
  <%= f.file_field :name, id: :inputFile %>
</div>
<div class="field">
  <%= f.label :description %><br>
  <%= f.text_field :description, class: "form-control" %>
</div>
<div class="field">
  <%= f.label :open_date %><br>
  <%= f.text_field :open_date, class: "form-control", id: "datetimepicker1" %>
</div>
<div class="field">
  <%= f.label :close_date %><br>
  <%= f.text_field :close_date, class: "form-control", id: "datetimepicker2" %>
</div>
<div class="field">
  <%= f.label :limit %><br>
  <%= f.number_field :limit, class: "form-control" %>
</div>
<div class="field checkbox">
  <label>
    <%= f.check_box :visible %>表示/非表示
  </label>
</div>
<div class="field checkbox">
  <label>
    <%= f.check_box :comment_able %>コメント可/不可
  </label>
</div>
<div class="actions">
  <%= f.submit '登録', class: "btn btn-primary btn-lg" %>
</div>
<%= f.hidden_field :user_id, value: current_user.id %>
<% end %>

app/views/post_images/edit.html.erb
<div class="container-fluid">
  <h1>Editing post_image</h1>

    <div class="row center-block">

      <div class="col-md-offset-3 col-md-6">
        <div class="well bs-component">
          <%= render 'form' %>
        </div>
        <%= link_to 'Show', @post_image,      {class: "btn btn-default"} %> |
        <%= link_to 'Back', post_images_path, {class: "btn btn-default"} %>
      </div>

    </div>

</div>

app/views/post_images/index.html.erb
<div class="container-fluid">
  <div class="row center-block">
    <div class="col-md-12">

      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th class="col-xs-10 col-md-4">Name</th>
            <th class="hidden-xs col-md-4">Description</th>
            <th class="hidden-xs col-md-2">Visible</th>
            <th class="col-xs-2  col-md-2"></th>
          </tr>
        </thead>

        <tbody>
          <% @post_images.each do |post_image| %>
            <tr>
              <td><%= image_tag post_image.name.url, class: "img-responsive" %></td>
              <td class="hidden-xs col-md-4"><%= post_image.description %></td>
              <td class="hidden-xs col-md-2"><%= post_image.visible %></td>
              <td>
                <%= link_to 'Show', post_image, {class: "btn btn-flat btn-success"} %><br>
                <%=
                    link_to 'Edit',
                    edit_post_image_path(post_image),
                    {class: "btn btn-flat btn-info"}
                %><br>
                <%=
                    link_to 'Destroy',
                    post_image,
                    method: :delete,
                    class: "btn btn-flat btn-danger",
                    data: { confirm: 'Are you sure?' }
                %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= paginate @post_images %>

      <br>

      <%= link_to 'New Post image', new_post_image_path, {class: "btn btn-default"} %>

    </div>
  </div>
</div>

app/views/post_images/new.html.erb
<div class="container-fluid">
  <h1>New post_image</h1>

    <div class="row center-block">

      <div class="col-md-offset-3 col-md-6">
        <div class="well bs-component">
          <%= render 'form' %>
        </div>
        <%= link_to 'Back', post_images_path, {class: "btn btn-default"} %>
      </div>

    </div>

</div>

app/views/post_images/show.html.erb
<div class="container-fluid">
  <div class="row center-block">
    <div class="col-md-offset-3 col-md-6">
      <div class="well bs-component">
        <p id="notice"><%= notice %></p>

        <p>
          <strong>Name:</strong>
          <%= @post_image.name %>
        </p>

        <p>
          <%= image_tag @post_image.name.url, class: "img-responsive" %>
        </p>

        <p>
          <strong>Name:</strong>
          <%= @post_image.description %>
        </p>

        <p>
          <strong>User:</strong>
          <%= @post_image.user_id %>
        </p>

        <p>
          <strong>Open date:</strong>
          <%= @post_image.open_date %>
        </p>

        <p>
          <strong>Close date:</strong>
          <%= @post_image.close_date %>
        </p>

        <p>
          <strong>Limit:</strong>
          <%= @post_image.limit %>
        </p>

        <p>
          <strong>Visible:</strong>
          <%= @post_image.visible %>
        </p>

        <p>
          <strong>Comment able:</strong>
          <%= @post_image.comment_able %>
        </p>

        <p>
          <strong>Deleted at:</strong>
          <%= @post_image.deleted_at %>
        </p>

        <%= link_to 'Edit', edit_post_image_path(@post_image), {class: "btn btn-flat btn-info"} %> |
        <%= link_to 'Back', post_images_path, {class: "btn btn-default"} %>

      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<header class="jumbotron">
  <div class="container">
    <h1>Header を作る</h1>
    <p>今回はBootrapでヘッダー画像の部分を作る。基本的なHTMLのひな形に、背景を指定するだけでそれっぽく作ることが可能。綺麗に見せるコツは背景の画像をどうのように使いこなすかによって大きく変わってきます。ボカシを与えると、遠近感の視覚効果を与えることが出来ます</p>
    <p><a class="btn btn-lg midashi-btn" role="button">もっと詳しく &raquo;</a></p>
  </div>
</header>

<h1>Welcom#index</h1>
<p>Find me in app/views/welcom/index.html.erb</p>